apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daytrader-web
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - hosts:
        - {{ .Values.cluster.dns }}
      secretName: daytrader-web
  rules:
    - host: {{ .Values.cluster.dns }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: daytrader-web
                port:
                  number: 5443